"$schema" = 'https://starship.rs/config-schema.json'

# A minimal left prompt
format = """
$all\
${custom.firebase}\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[git_metrics]
disabled=false

[time]
disabled=false

[status]
disabled=false

[shell]
disabled=false

[shlvl]
disabled=false

[custom.firebase]
command = "$DOTFILES/scripts/starship-firebase/command.sh"
detect_files = []
when = """ [[ -n $($DOTFILES/scripts/starship-firebase/get_firebase_dir.sh) ]] """
symbol = "🔥"
style = "bold yellow"
format = "[$symbol $output]($style) "
shell = ["bash", "--noprofile", "--norc"]

