# Set directory for dotfiles repo
export DOTFILES="$HOME/.dotfiles"

if [ $(uname -p) = 'arm' ]; then
  eval "$(/opt/Homebrew/bin/brew shellenv)"
else
  eval "$(/usr/local/Homebrew/bin/brew shellenv)"
fi

function exists () {
  command -v $1 >/dev/null 2>&1
}